version: "3"
services:
  # Workspace
  workspace:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspaces/dynasc:cached
    env_file:
      - ../.env
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
  # DynamoDB
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
  # DynamoDB Admin
  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
  # Lambda
  lambda:
    build:
      context: ./lambda
    ports:
      - "8080:8080"
    entrypoint: "/usr/local/bin/aws-lambda-rie /var/runtime/bootstrap"
