name: test
run-name: Test by @{{ github.actor }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      dynamodb:
        # Docker Hub image
        image: amazon/dynamodb-local
        ports:
          - "8000:8000"
        options: >-
          --health-cmd "curl -s http://localhost:8000 -o /dev/null || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3

      - name: Go Test
        run: go test -v ./...
